all:
	@g++ main.c -o out.exe
	@./out.exe	
prop:
	@g++ ./proper_imp.c -o propout.exe
	@./propout.exe	
mov:
	@g++ ./mem_mov_fun.c -o mem.exe
	@./mem.exe	
gen:
	@g++ ./generic_imp.c -o gen.exe
	@./gen.exe	
